import 'dart:convert';

class Src {
  String original;
  String large2x;
  String large;
  String medium;
  String small;
  String portrait;
  String landscape;
  String tiny;
  Src({
    this.original,
    this.large2x,
    this.large,
    this.medium,
    this.small,
    this.portrait,
    this.landscape,
    this.tiny,
  });

  Map<String, dynamic> toMap() {
    return {
      'original': original,
      'large2x': large2x,
      'large': large,
      'medium': medium,
      'small': small,
      'portrait': portrait,
      'landscape': landscape,
      'tiny': tiny,
    };
  }

  factory Src.fromMap(Map<String, dynamic> map) {
    if (map == null) return null;

    return Src(
      original: map['original'],
      large2x: map['large2x'],
      large: map['large'],
      medium: map['medium'],
      small: map['small'],
      portrait: map['portrait'],
      landscape: map['landscape'],
      tiny: map['tiny'],
    );
  }

  String toJson() => json.encode(toMap());

  factory Src.fromJson(String source) => Src.fromMap(json.decode(source));
}

class Photos {
  int id;
  int width;
  int height;
  String url;
  String photographer;
  String photographerUrl;
  int photographerId;
  Src src;
  bool liked;
  Photos({
    this.id,
    this.width,
    this.height,
    this.url,
    this.photographer,
    this.photographerUrl,
    this.photographerId,
    this.src,
    this.liked,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'width': width,
      'height': height,
      'url': url,
      'photographer': photographer,
      'photographerUrl': photographerUrl,
      'photographerId': photographerId,
      'src': src?.toMap(),
      'liked': liked,
    };
  }

  factory Photos.fromMap(Map<String, dynamic> map) {
    if (map == null) return null;

    return Photos(
      id: map['id'],
      width: map['width'],
      height: map['height'],
      url: map['url'],
      photographer: map['photographer'],
      photographerUrl: map['photographerUrl'],
      photographerId: map['photographerId'],
      src: Src.fromMap(map['src']),
      liked: map['liked'],
    );
  }

  String toJson() => json.encode(toMap());

  factory Photos.fromJson(String source) => Photos.fromMap(json.decode(source));
}

class Autogenerated {
  int totalResults;
  int page;
  int perPage;
  List<Photos> photos;
  String nextPage;
  Autogenerated({
    this.totalResults,
    this.page,
    this.perPage,
    this.photos,
    this.nextPage,
  });

  Map<String, dynamic> toMap() {
    return {
      'totalResults': totalResults,
      'page': page,
      'perPage': perPage,
      'photos': photos?.map((x) => x?.toMap())?.toList(),
      'nextPage': nextPage,
    };
  }

  factory Autogenerated.fromMap(Map<String, dynamic> map) {
    if (map == null) return null;

    return Autogenerated(
      totalResults: map['totalResults'],
      page: map['page'],
      perPage: map['perPage'],
      photos: List<Photos>.from(map['photos']?.map((x) => Photos.fromMap(x))),
      nextPage: map['nextPage'],
    );
  }

  String toJson() => json.encode(toMap());

  factory Autogenerated.fromJson(String source) =>
      Autogenerated.fromMap(json.decode(source));
}
